// Mocks generated by Mockito 5.4.4 from annotations
// in vegan_cibum/test/recipe_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:vegan_cibum/data/models/recipe_model.dart' as _i4;
import 'package:vegan_cibum/data/service/http/api_service_http.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ApiServiceHttp].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiServiceHttp extends _i1.Mock implements _i2.ApiServiceHttp {
  @override
  _i3.Future<List<_i4.RecipeModel>> fetchRecipe() => (super.noSuchMethod(
        Invocation.method(
          #fetchRecipe,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.RecipeModel>>.value(<_i4.RecipeModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.RecipeModel>>.value(<_i4.RecipeModel>[]),
      ) as _i3.Future<List<_i4.RecipeModel>>);
}
